export const histoire = [
    [
        {
            chara: "NARRATEUR",
            texte: "Tout commence tranquillement à Green Hill, Sonic est posé dehors avec ses amis entrain de manger des chili-dogs, Amy qui est amoureuse de lui va se diriger vers lui pour entamer une conversation.",
            background: "url(./img/01_Sonic_plage.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "AMY",
            texte: "Alors Sonic, comment trouves-tu mes chili-dogs, je les ai faits avec amour, tu sais ?",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Un vrai régal, Amy ! Tu devrais en faire plus souvent !",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "AMY",
            texte: "Avec plaisir ! Est-ce que ça te dirait qu'on se voit demain rien que nous deux...",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Ah non, désolé mais demain on part à la recherche de la 7ème émeraude, sinon Eggman va encore nous envoyer ses robots de malheur !",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "AMY",
            texte: "Oh je comprends, peut-être une autre fois...",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "En voyant qu'Amy rate sa tentative, Tails s'approche des deux",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "TAILS",
            texte: "Désolé Sonic mais le radar est tombé en panne, on va reporter la recherche à demain !",
            background: "url(./img/03_tails_amy.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Oh non, vraiment ? Bon bah tant pis, je suis libre demain du coup !",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "AMY",
            texte: "Super !",
            background: "url(./img/02_Sonic_Amy2.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Voilà Eggman qui arrive dans une pièce sombre d'un bâtiment abandonné, assis sur une chaise tout en scrutant des documents",
            background: "url(./img/04_eggman_papier.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "EGGMAN",
            texte: "Les documents de mon grand-père décédé... Je devrai trouver quelque chose d'intéressant",
            background: "url(./img/04_eggman_papier.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "En cherchant parmi le bazar de paperasses, Eggman tombe sur une étrange télécommande avec un gros bouton rouge où il est écrit de ne pas appuyer",
            background: "url(./img/05_boutonrouge.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "EGGMAN",
            texte: "Désolé grand-père mais ma curiosité n'a aucune limite !",
            background: "url(./img/05_boutonrouge.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "En appuyant sur le bouton, une alarme se délenche et la porte de la pièce se referme, ne laissant aucun moyen de sortie à Eggman",
            background: "url(./img/06_effrayer.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "EGGMAN",
            texte: "Non, je suis trop jeune pour mourrir !",
            background: "url(./img/06_effrayer.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Pensant que sa fin était proche, une tube sort au centre de la pièce et quelque chose ou plutôt quelqu'un en sort, regardant Eggman d'un air neutre",
            background: "url(./img/06_effrayer.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "???",
            texte: "Qui es-tu ? Qu'est-ce que je fais ici ?",
            background: "url(./img/07_silhouette.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "EGGMAN",
            texte: "Impensable, je pensais que c'était qu'une légende mais l'expérience ratée existe bel et bien, une expérience capable d'éradiquer l'humanité entière, c'est pour cela que mon grand-père l'a abandonné au profit de Shadow, cet être est un réel danger mais si je parviens à le contrôler...",
            background: "url(./img/07_silhouette.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Eggman sort un grand sourire, il ordonne à l'être de pulvériser la porte, ce qu'il fait sans problème en une attaque et on peut entendre Eggman rire de malveillance en fond...",
            background: "url(./img/07_silhouette.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "De retour dans le point de vue de Sonic, une énorme explosion va se faire voir un peu plus loin du groupe, nos amis seront surpris par cette explosion",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "C'était quoi ça ?!",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "KNUCKLES",
            texte: "C'est sûrement encore un coup de cet enfoiré d'Eggman, on devrait aller voir !",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Je vais aller voir !",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "TAILS",
            texte: "Attends Sonic, le radar fonctionne à nouveau, je vais aller chercher la 7ème émeraude, on ne sait jamais !",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "KNUCKLES",
            texte: "Parfait ! Sonic et moi, on va aller lui botter les fesses en attendant !",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
            choix: {
                choixNom1: "CHOIX 1",
                choixNom2: "CHOIX 2",
                choixChapitre1: 2,
                choixTexte1: "Knuckles accompagne Sonic",
                choixTexte2: "Knuckles accompagne Tails",
            },
        },
        {
            scenePosition: 27,
            chara: "SONIC",
            texte: "Non Knuckles, accompagne Tails, on ne sait jamais ce qui peut arriver à Tails sur le chemin mais moi j'arriverai à m'en sortir, je suis ultra rapide, n'oublie pas !",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "AMY",
            texte: "Faites très attention à vous, s'il vous plait...",
            background: "url(./img/08_sonic_bande.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "T'inquiète pas, ce n'est que Eggman, peu importe ce qu'il trame, il n'arrivera jamais à me vaincre ! Sur ce...",
            background: "url(./img/09_sonic_pouce.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic les salue d'un geste de la main et fonce alors seul vers l'endroit où l'explosion a surgi",
            background: "url(./img/09_sonic_pouce.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },

        /////// FIN CHAPITRE 1 ////////

        {
            chara: "NARRATEUR",
            texte: "Sonic court alors vers le lieu de l'explosion et il remarque que d'autres explosions apparaissent pratiquement au même endroit, il accélère la cadence et pendant sa course, il tombe sur une horde de robots d'Eggman en rond mais ils n'ont pas l'air de vous avoir remarquer, que faites-vous ?",
            background: "url(./img/10_robots.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            background: "url(./img/10_robots.webp)",
            choix: {
                choixNom1: "CHOIX 1",
                choixNom2: "CHOIX 2",
                choixChapitre2: 3,
                choixTexte1: "Se débarasser des robots",
                choixTexte2: "Les ignorer et partir discrètement",
                music: "./sounds/ost_jeu_1.mp3",
            },
        },
        {
            chara: "SONIC",
            texte: "Hé, les bouts de ferrailles, venez que je vous fasse votre fête !",
            background: "url(./img/10_robots.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Il se met en boule et leur fonce dessus pour les exploser, pendant son attaque, il remarque son ami Cream qui était en pleures à cause de ces robots qui l'agressent",
            background: "url(./img/11_cream_danger.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Cream ! Tiens bon !",
            background: "url(./img/11_cream_danger.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic se débarasse plutôt facilement des robots en leur fonçant dessus avec une grande vitesse et il aidera Cream à se relever ensuite",
            background: "url(./img/11_cream_danger.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Ils t'ont pas blessé, j'espère ?",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "CREAM",
            texte: "Non, grâce à toi, merci Sonic",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Bien sûr ! Toujours là pour mes amis !",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "CREAM",
            texte: "Attends Sonic, tu sais ce qu'il se passe ? C'est quoi toutes ces explosions ?",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "J'en sais pas plus que toi, Cream. Ca doit être cette tête d'oeuf d'Eggman et le connaissant, il doit avoir quelque chose derrière la tête",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "CREAM",
            texte: "Ah oui, j'ai failli oubliée ! Pendant que j'essayais de fuir les robots, j'ai vu quelqu'un qui te ressemblait comme deux gouttes d'eau, je n'ai pu le voir que de loin mais je pensais que c'était toi ",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Quelqu'un qui me ressemble ? C'était peut-être Shadow ?",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "CREAM",
            texte: "Non, il avait des traits bleus comme toi et je l'ai vu se diriger vers le lieu de l'explosion avant que cela se produise",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Je vois... Je vais aller voir, rends-toi à la plage, Amy et Biggy se trouvent là-bas en ce moment même, tu y seras plus en sécurité",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "CREAM",
            texte: "D'accord, fais attention à toi, Sonic !",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic lui fait un clin d'oeil avant de repartir en direction du lieu de l'explosion",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Après seulement quelques minutes, Sonic arrive sur les lieux mais étrangement, il n'y a rien, personne, juste des cratères causés par les explosions mais aucune traçe d'ennemi ou d'un soi-disant double de lui",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Bizarre aucune trace d'Eggman, où ont-ils bien pu disparaitre ? Je vais essayer d'appeler Tai...",
            background: "url(./img/12_sonic_cream.jpeg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Il n'a même pas l'occasion de finir sa phrase qu'il se prend un coup au visage assez violent qui le fera valser un peu plus loin, il tousse et essaie de reprendre ses esprits tout en levant la tête, devant lui se tenait Shadow l'hérisson, son rival de toujours",
            background: "url(./img/13_shadow_poing.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Shadow ?! Tu sais que tu n'es pas obligé de m'attaquer à chacune de nos retrouvailles",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Ce n'est pas le moment de rigoler, Sonic ! On vient à peine de régler l'histoire avec le Prisme et Nine que tu nous ramènes déjà de nouveaux problèmes !",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Woh woh, calme-toi ! Je n'ai rien à voir avec ça cette fois-ci !",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Menteur !",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Non, vraiment ! J'ai retenu ma leçon depuis le Prisme du paradoxe ! Puis comment tu as fait pour me retrouver ?",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Humm... J'ai croisé ton amie lapine sur le chemin, elle m'a dit où tu te rendais",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Bah voilà, tu sais bien que je suis innocent, pourquoi tu m'as frappé alors ?",
            background: "url(./img/14_shadow_menace.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "J'avais juste envie",
            background: "url(./img/15_shadow_nargue.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Très sympa de ta part, franchement, moi qui pensait qu'on était comme deux frères",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Bah retire cette pensée de ton crâne vide et rentrons dans le vif du sujet, que sais-tu sur ce qu'il se passe ?",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Eggman est sûrement dans le coup, je ne vois personne d'autre. Cream m'a dit qu'elle avait vu une personne qui me ressemblait comme deux gouttes d'eau, je pensais à toi au début mais elle m'a dit qu'il avait les mêmes traits bleu que moi mais quand je suis arrivé ici, il y avait personne",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Un hérisson ? Je pensais qu'on était les deux seuls restants mais on dirait bien que non. Et si c'était un piège en réalité ?",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Un piège ?",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Oui pour t'attirer ici et en profiter pour faire quelque chose d'autre ?",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Pas bête, Shadow ! Mais qu'est-ce qu'ils veulent exactement... ?",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "???",
            texte: "Sonic, Shadow ! C'était un piège d'Eggman, montez vite !",
            background: "url(./img/16_sonic_assis_shadow.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic lève la tête et voit Tails qui débarque avec son avion, Knuckles est là aussi, Sonic et Shadow vont sauter sur l'avion quand celui-ci frôle le sol près d'eux",
            background: "url(./img/17_tails_avion.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "TAILS",
            texte: "Ils en ont après la master emerald ! On doit se dépêcher !",
            background: "url(./img/17_tails_avion.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "La master emerald ? Pourquoi ?",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "KNUCKLES",
            texte: "Je m'en fiche du pourquoi mais s'il ose ne serait-ce que toucher à mon précieux, il va avoir de mes nouvelles !",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "TAILS",
            texte: "Accrochez-vous, je vais mettre le turbo !",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Tails appuie sur un bouton et la vitesse de l'avion augmente considérablement, le groupe se dirigeant vers le temple où se trouve la master emerald",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "J'ai un mauvais pressentiment...",
            background: "url(./img/19_shadow_inquiet.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },

        ///////// FIN CHAPITRE 2 ///////////////

        {
            chara: "NARRATEUR",
            texte: "Après seulement quelques minutes de vol, les héros arrivent finalement au temple et peuvent déjà voir Eggman au loin avec une personne se tenant à ses côtés",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "TAILS",
            texte: "On est arrivés, sautez ! Knuckles et moi avons un plan, et prenez ça aussi !",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Tails donne les 7 chaos emerald à Sonic et ce dernier et Shadow vont sauter de l'avion, atterissant devant Eggman et l'autre fameux hérisson",
            background: "url(./img/18_sonic_avion.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Bah alors, Eggman ? Je te manque tellement ces derniers temps que tu as pris un double de moi ?",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "EGGMAN",
            texte: "Rira bien qui rira le dernier, Sonic ! Ta misérable vie va prendre fin aujourd'hui, grâce à son aide !",
            background: "url(./img/21_eggman_vs_sonic.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "C'est donc toi qui te fais passer pour moi, ces dernier temps ? Qui es-tu ?",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Je me présente, Seelkadoom. Le grand-frère de Shadow, en quelque sorte",
            background: "url(./img/22_seelkadoom.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Hein ?! Tu m'as jamais mit au courant de ça, Shadow !",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Je n'en savais rien non plus, attends un peu... Ton nom me dit quelque chose, Seelkadoom... Tu ne serais pas le projet abandonné ?! ",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Bravo, belle perspicacité, Shadow... Je suis venu ici pour reprendre ce qui m'est dû, le pouvoir du Chaos que tu m'as volé ! C'est moi qui aurait dû l'avoir et dominer ce monde, ce que tu n'as pas réussi à faire ! Allez, viens à moi, petit frère. Ensemble, nous deviendrons parfaits... ",
            background: "url(./img/22_seelkadoom.webp)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Dans tes rêves ! Allez, débarassons-nous de lui au plus vite, Sonic. Il commence à me taper sur les nerfs.",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Hehe pour une fois que je suis d'accord avec toi, Shadow !",
            background: "url(./img/20_sonic_vs_eggman.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Les 7 chaos emeralds gravitent autour de Sonic et Shadow, une lumière jaune les entourera un bref instant avec que ces deux ne s'éveillent, voici Super Sonic et Super Shadow",
            background: "url(./img/23_super.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Voilà donc la fameuse forme Super... Intéressant...",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Je suis désolé pour toi, Seelkadoom, mais c'est déjà la fin pour toi ! ",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Une vieille teinture jaune ne suffit pas à me faire peur ! Venez à moi ! Venez à Seelkadoom ! Votre tombeau n'attend que...",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Attends juste deux secondes, veux-tu ? Je veux pas te couper dans ton monologue mais on doit se départager avant pour savoir qui va t'affronter !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Quoi... ?",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Le premier à un, Shadow ! Pierre, feuille, ciseaux !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Pierre, feuille, ciseaux !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            miniGame: "pierrePapierCiseaux",
            music: "./sounds/ost_jeu_1.mp3",
        },

        // bon du coup là t'a le pierre feuille ciseaux puis ca reprend avec la victoire de Sonic

        {
            chara: "SONIC",
            texte: "Hehe, j'ai gagné !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            condition: "playerStory === 'sonic'",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Qu'est-ce que je fous ici moi...",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Pfff... Vas-y, dépêche-toi pour qu'au moins on en finisse rapidement !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Allez à nous deux, Seelkadoom !",
            background: "url(./img/27_super_sonic_serieux.jpg)",
            music: "./sounds/ost_jeu_1.mp3",
        },

        {
            fight: true,
            playerStory: "sonic",
            ennemyStory: "seelkadoom",
            win: 4,
        },
    ],
    [
        {
            chara: "SHADOW",
            texte: "On dirait bien que c'est moi qui ait gagné",
            background: "url(./img/24_seelkadoom_shadow.png)",
            condition: "playerStory === 'shadow'",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SONIC",
            texte: "Pas juste ! C'est toujours toi qui gagne !",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Je suis juste meilleur",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SEELKADOOM",
            texte: "Qu'est-ce que je fous ici moi...",
            background: "url(./img/24_seelkadoom_shadow.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            chara: "SHADOW",
            texte: "Allez, prépare-toi à affronter la forme de vie ultime, Seelkadoom !",
            background: "url(./img/28_super_shadow_serieux.png)",
            music: "./sounds/ost_jeu_1.mp3",
        },
        {
            fight: true,
            playerStory: "shadow",
            ennemyStory: "seelkadoom",
            win: 4,
        },
        {
            chara: "SEELKADOOM",
            texte: "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHA !!!!",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "NARRATEUR",
            texte: "Mauvaise fin ! Appuyez sur le bouton Reset au dessus à droite pour recommencer le jeu",
            background: "url(./img/22_seelkadoom.webp)",
        },
    ],
    [
        {
            chara: "SONIC",
            texte: "Ouais, suis-moi Knuckles ! Et fais bien attention à toi Tails surtout",
            background: "url(./img/08_sonic_bande.png)",
        },
        {
            chara: "TAILS",
            texte: "T'en fais pas pour moi, je gère !",
            background: "url(./img/08_sonic_bande.png)",
        },
        {
            chara: "AMY",
            texte: "Faites bien attention à vous, s'il vous plait",
            background: "url(./img/08_sonic_bande.png)",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic fait un clin d'oeil à Amy avant de partir avec Knuckles en direction du lieu de l'explosion, Tails part chercher la 7ème émeraude avec son avion. Après une dixaine de minutes, Sonic et Knuckles arrivent au temple de la master emerald, ayant appris de la part de Tails que c'était en réalité un piège",
            background: "url(./img/29_sonic_knuckles.jpg)",
        },
        {
            chara: "SONIC",
            texte: "Bah alors, Eggman ? Je te manque tellement que t'a dégôté un double de moi pour être ton ami ? Comme c'est mignon.",
            background: "url(./img/29_sonic_knuckles.jpg)",
        },
        {
            chara: "EGGMAN",
            texte: "Rira bien qui rira le dernier, Sonic ! Et je rigolerai moins en sachant sur qui est-ce que je suis tombé, hahahaha...",
            background: "url(./img/21_eggman_vs_sonic.jpg)",
        },
        {
            chara: "NARRATEUR",
            texte: "Tout d'un coup, quelque chose va s'envoler derrière un buisson, c'était Tails et il a été capturé par Eggman, il est actuellement KO et ne répond pas aux cris de Sonic.",
            background: "url(./img/21_eggman_vs_sonic.jpg)",
        },
        {
            chara: "SEELKADOOM",
            texte: "Et oui, on est tombé sur votre petit ami le renard qui fouillait un peu trop dans nos affaires à mon goût",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SONIC",
            texte: "Enflure, rendez-le-moi !",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SEELKADOOM",
            texte: "Vous pouvez lui dire adieu, considérez ça comme une mise en garde de ma part",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "NARRATEUR",
            texte: "Seelkadoom envoie un rayon d'énergie sur Tails qui s'écroule sans vie devant les yeux de Sonic et Knuckles",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SONIC",
            texte: "TAILS ! NOOOOOOOOON !",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SEELKADOOM",
            texte: "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA !!!",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "NARRATEUR",
            texte: "Mauvaise fin ! Appuyez sur le bouton Reset au dessus à droite pour recommencer le jeu",
            background: "url(./img/22_seelkadoom.webp)",
        },
    ],
    [
        {
            chara: "SONIC",
            texte: "Pas le temps de m'occuper d'eux, je dois me dépêcher !",
            background: "url(./img/10_robots.webp)",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic va alors esquiver les robots et se diriger vers le temple où se trouve la master emerald et Eggman, il y arrive seul et tombe sur lui et sur un être qui lui ressemble vachement beaucoup...",
            background: "url(./img/10_robots.webp)",
        },
        {
            chara: "SONIC",
            texte: "T'es qui toi ?! Pourquoi tu me ressembles autant !",
            background: "url(./img/30_sonic_seul.jpg)",
        },
        {
            chara: "SEELKADOOM",
            texte: "On pourrait dire que je suis une forme évoluée de toi même plus que Shadow je dirais même",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SONIC",
            texte: "Je comprends rien à ce que tu racontes mais j'espère pour toi que tu n'as rien fait à mes amis !",
            background: "url(./img/30_sonic_seul.jpg)",
        },
        {
            chara: "SEELKADOOM",
            texte: "En parlant de ça, tu n'aurais pas oublié un petit quelqu'un ?",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "NARRATEUR",
            texte: "Il ramasse le cadavre mort de Cream et balance sous les yeux de Sonic",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SONIC",
            texte: "Cream ?! Non ! Pourquoi ?!!",
            background: "url(./img/22_seelkadoom.webp)",
        },
        {
            chara: "SEELKADOOM",
            texte: "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHA !!!!",
            background: "url(./img/22_seelkadoom.webp)",
        },
    ],
    [
        {
            chara: "SONIC",
            texte: "Adieu, Seelkadoom...",
            background: "url(./img/31_hyper_sonic.png)",
            music: "./sounds/ost_final.mp3",
        },
        {
            chara: "NARRATEUR",
            texte: "Sonic envoie un gigantesque rayon d'énergie sur Seelkadoom, ce dernier va s'écrouler au sol, étant entre la vie et la mort",
            background: "url(./img/31_hyper_sonic.png)",
        },
        {
            chara: "SEELKADOOM",
            texte: "...",
            background: "url(./img/32_seelkadoom_ko.png)",
        },
        {
            chara: "SHADOW",
            texte: "C'est enfin fini...",
            background: "url(./img/33_shadow_soulager.png)",
        },
        {
            chara: "KNUCKLES",
            texte: "On y a tous survécus, c'est un miracle...",
            background: "url(./img/34_knuckles.png)",
        },
        {
            chara: "SONIC",
            texte: "On dirait bien ! D'ailleurs, bon travail, Knuckles ! Tu es parvenu à reprendre la master emerald en secret, ce qui a beaucoup réduit la force de Seelkadoom !",
            background: "url(./img/35_sonic_souriant.png)",
        },
        {
            chara: "KNUCKLES",
            texte: "C'était juste un coup de bol, hehe...",
            background: "url(./img/34_knuckles.png)",
        },
        {
            chara: "SHADOW",
            texte: "Finissons-en avec lui maintenant, il va payer pour ce qu'il a fait !",
            background: "url(./img/36_shadow_agressif.png)",
        },
        {
            chara: "SONIC",
            texte: "Non, attends !",
            background: "url(./img/36_shadow_agressif.png)",
        },
        {
            chara: "SHADOW",
            texte: "Mais pourquoi tu m'arrêtes ! Tu connais bien le risque de le laisser en vie, on peut pas ignorer ça !",
            background: "url(./img/36_shadow_agressif.png)",
        },
        {
            chara: "SONIC",
            texte: "Je sais bien ! Mais sans les chaos emerald, il ne peut rien faire à présent et puis je suis sûr qu'il est juste perdu et qu'il a un bon fond finalement",
            background: "url(./img/35_sonic_souriant.png)",
        },
        {
            chara: "SHADOW",
            texte: "Pff... Fais ce que tu veux...",
            background: "url(./img/36_shadow_agressif.png)",
        },
        {
            chara: "KNUCKLES",
            texte: "Qu'est-ce qu'on fait maintenant ?",
            background: "url(./img/34_knuckles.png)",
        },
        {
            chara: "SONIC",
            texte: "Retournons là où tout a commencé ! À la mer aussi cool et bleue que moi !",
            background: "url(./img/37_adieu.png)",
        },
        {
            chara: "NARRATEUR",
            texte: "Et c'est ainsi que prend fin ce chapitre de la vie de Sonic, mais rassurez-vous, d'autres aventures palpitantes attendent notre jeune hérisson préféré !",
            background: "url(./img/37_adieu.png)",
        },
        {
            chara: "NARRATEUR",
            texte: "Merci beaucoup d'avoir joué ! Le jeu est fini et il ne reste plus rien à faire, vous pouvez quitter la page ou bien appuyer sur le bouton reset en haut à droite pour découvrir les autres routes !",
            background: "url(./img/38_fin.jpg)",
        },
    ],
];
